version: '3.8'
services:
  db:
    image: postgres:16.0-alpine3.17
    volumes:
      - ./data/db:/var/lib/postgresql/dataUsers
    env_file:
      - UserManager/.env
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user_manager:
    build: UserManager/.
    env_file:
      - UserManager/.env
    ports:
      - "8001:8000"
    command: >
      sh -c "sleep 10 &&
                  alembic stamp head &&
                  alembic revision --autogenerate -m 'Initial migration' &&
                  alembic upgrade head &&
                  python -m uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
      - ./certs:/app/certs
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: "redis:alpine"

  # password
  db_pass:
    image: postgres:16.0-alpine3.17
    volumes:
      - ./data/db_pass:/var/lib/postgresql/dataPasswords
    env_file:
      - PasswordManager/.env
    ports:
      - "5435:5434"
    command: postgres -p 5434
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h db_pass -p 5434" ]
      interval: 10s
      timeout: 5s
      retries: 5

  password_manager:
    build: PasswordManager/.
    env_file:
      - PasswordManager/.env
    ports:
      - "8003:8002"
    command: >
      sh -c "sleep 20 &&
                  alembic stamp head &&
                  alembic revision --autogenerate -m 'Initial migration' &&
                  alembic upgrade head &&
                  python -m uvicorn main:app --host 0.0.0.0 --port 8002"
    volumes:
      - .:/app
    depends_on:
       db_pass:
         condition: service_healthy

  redis_pass:
    image: "redis:alpine"
    ports:
      - "6380:6379"
